### ISSUE TITLE
Fix the alignment

### ISSUE THREAD

**Issue by Rupesh-Piwal** [Rupesh-Piwal/ResumeCraft#1]
![Screenshot (345)](https://github.com/Rupesh-Piwal/ResumeCraft/assets/97403179/2179e8fb-0957-4429-a716-8bb7a9932892)

**Comment by Samarthasbhat** [comment]
The aligment of the footer in the image ?

**Comment by Rupesh-Piwal** [comment]
yes, i am trying to give home page h-screen (height: 100vh) in tailwind CSS & flex property still not working!! finally fixed with position: absolute property.
![Uploading Screenshot (346).png…]()

**Comment by Samarthasbhat** [comment]
try this 

import React from "react";

const Footer = () => {
  return (
    <footer className="bg-indigo-600 py-6 absolute bottom-0 w-full">
      <div className="container mx-auto text-center text-white">
        <p>&copy; 2024 Resume Generator. All rights reserved.</p>
      </div>
    </footer>
  );
};

export default Footer;

**Comment by Samarthasbhat** [comment]
Nice
